In [1]:
import os
import random
import sys
if os.path.dirname(os.getcwd()) not in sys.path:
    sys.path.append(os.path.dirname(os.getcwd()))
import torch
import torch.nn as nn
import torchvision

import time
import copy
import numpy as np
from torchvision import transforms
from tqdm import tqdm
from torchsummary import summary

print(f"torch = {torch.__version__}")
print(f"torchvision = {torchvision.__version__}")


torch = 1.12.1
torchvision = 0.13.1


In [2]:
from models import quat_mobilenet_v2
tiny_model = quat_mobilenet_v2(cifar10=True)
tiny_model.load_state_dict(torch.load("../models/weights/tiny_mobilenetv2_cifar.pt"))
summary(tiny_model,(3,32,32),device='cpu')

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
         QuantStub-1            [-1, 3, 32, 32]               0
            Conv2d-2           [-1, 32, 16, 16]             864
       BatchNorm2d-3           [-1, 32, 16, 16]              64
             ReLU6-4           [-1, 32, 16, 16]               0
            Conv2d-5           [-1, 32, 16, 16]             288
       BatchNorm2d-6           [-1, 32, 16, 16]              64
             ReLU6-7           [-1, 32, 16, 16]               0
            Conv2d-8           [-1, 16, 16, 16]             512
       BatchNorm2d-9           [-1, 16, 16, 16]              32
QuantizableInvertedResidual-10           [-1, 16, 16, 16]               0
           Conv2d-11           [-1, 64, 16, 16]           1,024
      BatchNorm2d-12           [-1, 64, 16, 16]             128
            ReLU6-13           [-1, 64, 16, 16]               0
           Conv2d-14         

In [3]:
min_val_cut = torch.tensor(-0.127)
max_val_cut = torch.tensor(0.127)

for name, param in tiny_model.named_parameters():
    print(param.dim())
    if param.dim()==4:
        y = param.clone()

        Min,Max = torch.aminmax(y, dim=1)
        Min = torch.min(Min,min_val_cut)
        Max = torch.max(Max,max_val_cut)

        s = (Max-Min)/(max_val_cut-min_val_cut)
        z = min_val_cut -torch.round(Min/s,decimals=3)
        
        for i in range(len(y)):
            y[i] = torch.round(y[i]/s[i]+z[i],decimals=3)
            y[i] = (y[i]-z[i])*s[i]
        param=y
    else:
        print(name,param)
        

4
1
features.0.1.weight Parameter containing:
tensor([0.5196, 0.5371, 0.2668, 0.4708, 0.2503, 0.2903, 0.4309, 0.2674, 0.5359,
        0.5124, 0.5269, 0.5179, 0.2491, 0.4390, 0.5380, 0.5384, 0.5445, 0.4856,
        0.3875, 0.3633, 0.5395, 0.5229, 0.5223, 0.4575, 0.5456, 0.5198, 0.4046,
        0.5033, 0.5404, 0.4906, 0.4406, 0.4894], requires_grad=True)
1
features.0.1.bias Parameter containing:
tensor([ 0.1546, -0.0500,  0.4752,  0.2713,  0.4899,  0.4603,  0.3403,  0.4740,
         0.0763,  0.1721,  0.1227,  0.1648,  0.4932,  0.3296,  0.0673,  0.0275,
        -0.0367,  0.2736,  0.3786,  0.4028, -0.0476,  0.1536,  0.1372,  0.3042,
         0.0187,  0.1481,  0.3765,  0.2018,  0.0308,  0.2339,  0.3379,  0.2315],
       requires_grad=True)
4
1
features.1.conv.0.1.weight Parameter containing:
tensor([0.5167, 0.5097, 0.5157, 0.4273, 0.6762, 0.6409, 0.4990, 0.5801, 0.4369,
        0.5996, 0.4290, 0.3597, 0.7089, 0.6622, 0.6199, 0.4657, 0.3474, 0.5844,
        0.4283, 0.5805, 0.3848, 0.4647, 0.

In [4]:
from utils import Data
train_loader, test_loader = Data.Cifar10_Dataloader(filepath="../data/")
for inputs, label in iter(train_loader):
    print(inputs.shape,len(inputs), inputs.size()[0])
    for i in range(inputs.size()[0]):
        temp = inputs[i].detach()
        print(temp)
        M = torch.max(temp)
        m = torch.min(temp)
        inputs[i] = torch.round(254*(inputs[i]-m)/(M-m)-127)/1000
        print(inputs[i])
        inputs[i] = (1000*inputs[i]+127)*(M-m)/254+m
    break

Files already downloaded and verified
Files already downloaded and verified
Train data set = 50000, Test = 10000
torch.Size([128, 3, 32, 32]) 128 128
tensor([[[-2.4291, -2.4291, -2.4291,  ..., -0.1416, -0.9558, -1.6343],
         [-2.4291, -2.4291, -2.4291,  ..., -1.3629, -1.9057, -2.1577],
         [-2.4291, -2.4291, -2.4291,  ..., -1.9638, -2.0608, -2.1964],
         ...,
         [-2.4291, -2.4291, -2.4291,  ..., -2.0026, -1.8863, -1.7506],
         [-2.4291, -2.4291, -2.4291,  ..., -1.2854, -1.3047, -1.3047],
         [-2.4291, -2.4291, -2.4291,  ..., -1.1884, -1.2078, -1.2466]],

        [[-2.4183, -2.4183, -2.4183,  ...,  0.0991, -0.7269, -1.5136],
         [-2.4183, -2.4183, -2.4183,  ..., -1.2579, -1.8282, -2.1036],
         [-2.4183, -2.4183, -2.4183,  ..., -1.9463, -2.0839, -2.1823],
         ...,
         [-2.4183, -2.4183, -2.4183,  ..., -1.9463, -1.7889, -1.6316],
         [-2.4183, -2.4183, -2.4183,  ..., -1.1792, -1.1792, -1.1596],
         [-2.4183, -2.4183, -2.4183,  .

In [5]:
for inputs, label in iter(train_loader):
        temp = inputs.detach()
        # inputs = inputs.flatten(start_dim=1)
        print(inputs.shape, torch.min(inputs.flatten(start_dim=1)))
        M = torch.max(torch.max(inputs),torch.full_like(inputs,torch.min(inputs)))
        m = torch.min(torch.min(inputs),torch.full_like(inputs,torch.max(inputs)))
        # M = torch.max(torch.max(inputs),torch.full_like(inputs,0.127))
        # m = torch.min(torch.min(inputs),torch.full_like(inputs,-0.127)) 
        print(M.size(),m.size())
        inputs = torch.round(254*(inputs-m)/(M-m)-127) /1000 
        for i in range(len(inputs)):
                print(torch.max(inputs[i]),torch.min(inputs[i]))
        # print(inputs)
        inputs = (1000*inputs+127)*(M-m)/254+m
        print(inputs.shape)

        break

torch.Size([128, 3, 32, 32]) tensor(-2.4291)
torch.Size([128, 3, 32, 32]) torch.Size([128, 3, 32, 32])
tensor(0.1270) tensor(-0.1270)
tensor(0.1000) tensor(-0.1270)
tensor(0.1140) tensor(-0.1270)
tensor(0.1200) tensor(-0.1270)
tensor(0.0470) tensor(-0.1270)
tensor(0.0730) tensor(-0.1270)
tensor(0.0610) tensor(-0.1270)
tensor(0.1040) tensor(-0.1270)
tensor(0.0600) tensor(-0.1270)
tensor(0.1150) tensor(-0.1270)
tensor(0.1160) tensor(-0.1270)
tensor(0.1270) tensor(-0.1270)
tensor(0.0810) tensor(-0.1270)
tensor(0.1250) tensor(-0.1270)
tensor(0.1100) tensor(-0.1270)
tensor(0.1260) tensor(-0.1270)
tensor(0.1270) tensor(-0.1270)
tensor(0.0950) tensor(-0.1080)
tensor(0.0850) tensor(-0.1270)
tensor(0.1270) tensor(-0.1270)
tensor(0.1240) tensor(-0.1270)
tensor(0.1140) tensor(-0.1270)
tensor(0.1260) tensor(-0.1270)
tensor(0.1070) tensor(-0.1140)
tensor(0.1270) tensor(-0.1270)
tensor(0.1100) tensor(-0.1270)
tensor(0.1090) tensor(-0.1270)
tensor(0.1200) tensor(-0.1270)
tensor(0.1080) tensor(-0.1270

In [6]:
min_val_cut = torch.tensor(-0.127)
max_val_cut = torch.tensor(0.127)

for name, param in tiny_model.named_parameters():
    if param.dim()==4:
        print(param.size())
        y = param.detach()
        y = torch.ones_like(y)
        print(y.size())
        Min,Max = torch.aminmax(y, dim=1)
        Min = torch.min(Min,min_val_cut)
        Max = torch.max(Max,max_val_cut)

        s = (Max-Min)/(max_val_cut-min_val_cut)
        z = min_val_cut -torch.round(Min/s,decimals=3)

        for i in range(y.size()[0]):
            y[i] = torch.round(y[i]/s[i]+z[i],decimals=3)
            y[i] = (y[i]-z[i])*s[i]
        
        print(y)
        break

torch.Size([32, 3, 3, 3])
torch.Size([32, 3, 3, 3])
tensor([[[[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]],

         [[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]],

         [[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]]],


        [[[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]],

         [[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]],

         [[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]]],


        [[[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]],

         [[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0.9983]],

         [[0.9983, 0.9983, 0.9983],
          [0.9983, 0.9983, 0

In [14]:
from models import mobilenetv2
quat_model = copy.deepcopy(tiny_model)
mobilenetv2.replace_relu(quat_model)
quat_model.fuse_model()
quat_model.train()
# activation - histogram , weight - perchannelMinMax
quat_model.qconfig = torch.quantization.get_default_qconfig("fbgemm")
quat_model = torch.quantization.prepare_qat(quat_model)
print(quat_model.state_dict())
# quat_model = torch.ao.quantization.convert(quat_model)
# torch.save(quat_model.state_dict(),"test.pt")
# quat_model.load_state_dict(torch.load("test.pt"))

/home/seunmul/.conda/envs/torch/lib/python3.9/site-packages/torch/ao/quantization/observer.py:176: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(


OrderedDict([('features.0.0.weight', tensor([[[[-4.3024e-02,  6.7154e-02,  9.5272e-02],
          [ 1.7945e-01,  2.1924e-01,  6.1055e-02],
          [ 1.4683e-01,  3.9568e-02,  4.9100e-02]],

         [[-7.4712e-02, -8.6489e-02, -5.2623e-02],
          [-1.8459e-02,  7.3853e-02,  4.8051e-02],
          [-5.2277e-02,  1.6962e-02, -2.6019e-02]],

         [[ 7.2391e-02,  3.0384e-02, -2.6148e-02],
          [-2.8106e-02,  1.0127e-01,  2.8089e-02],
          [ 6.1375e-02,  3.4317e-02, -2.0747e-02]]],


        [[[-6.2238e-02, -4.9491e-02, -1.2547e-01],
          [ 3.4807e-02,  4.7802e-03, -1.4045e-01],
          [-4.2575e-02, -5.7184e-02, -1.2847e-03]],

         [[-3.7178e-04,  4.8061e-02, -8.9484e-02],
          [-2.3019e-02, -8.5172e-03, -5.8778e-02],
          [ 5.2038e-02,  5.8702e-02, -1.5279e-01]],

         [[ 5.2330e-02, -1.1905e-02, -5.6586e-02],
          [-3.8074e-02,  4.4982e-02, -6.4364e-02],
          [-6.5232e-02, -5.3808e-02, -1.1233e-01]]],


        [[[ 2.2634e-02, -2.31